<a href="https://colab.research.google.com/github/juliano-fc/Airbnb/blob/main/stockmarket.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%cd /content/drive/MyDrive/Colab Notebooks

/content/drive/MyDrive/Colab Notebooks

             Adj Close
Date
2022-11-18  180.190002
2022-11-21  167.869995
2022-11-22  169.910004
2022-11-23  183.199997
2022-11-25  182.860001

In [ ]:
import pandas as pd
tsla = pd.read_csv("TSLA.csv",index_col="Date",parse_dates=["Date"],usecols=["Date","Adj Close"])
tsla.head()

In [ ]:
import yfinance as yf

ticker = "TSLA"
tesla_2023 = yf.download(ticker,start="2023-01-01",end="2023-11-17")
print(tesla_2023)
tesla_2023.info()

ibm_2023 = yf.download("IBM",start="2023-01-01",end="2023-11-17")
print(ibm_2023)

ibm_ytd = yf.download("IBM", period="ytd")
print(ibm_ytd)

[*********************100%%**********************]  1 of 1 completed
                  Open        High         Low       Close   Adj Close  \
Date
2023-01-03  118.470001  118.800003  104.639999  108.099998  108.099998
2023-01-04  109.110001  114.589996  107.519997  113.639999  113.639999
2023-01-05  110.510002  111.750000  107.160004  110.339996  110.339996
2023-01-06  103.000000  114.389999  101.809998  113.059998  113.059998
2023-01-09  118.959999  123.519997  117.110001  119.769997  119.769997
...                ...         ...         ...         ...         ...
2023-11-10  210.029999  215.380005  205.690002  214.649994  214.649994
2023-11-13  215.600006  225.399994  211.610001  223.710007  223.710007
2023-11-14  235.029999  238.139999  230.720001  237.410004  237.410004
2023-11-15  239.289993  246.699997  236.449997  242.839996  242.839996
2023-11-16  239.490005  240.880005  230.960007  233.589996  233.589996

               Volume
Date
2023-01-03  231402800
2023-01-04  180389000
2023-01-05  157986300
2023-01-06  220911100
2023-01-09  190284000
...               ...
2023-11-10  130994000
2023-11-13  140447600
2023-11-14  149771600
2023-11-15  150354000
2023-11-16  136816800

[221 rows x 6 columns]
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 221 entries, 2023-01-03 to 2023-11-16
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       221 non-null    float64
 1   High       221 non-null    float64
 2   Low        221 non-null    float64
 3   Close      221 non-null    float64
 4   Adj Close  221 non-null    float64
 5   Volume     221 non-null    int64
dtypes: float64(5), int64(1)
memory usage: 12.1 KB
[*********************100%%**********************]  1 of 1 completed
                  Open        High         Low       Close   Adj Close  \
Date
2023-01-03  141.100006  141.899994  140.479996  141.550003  134.852539
2023-01-04  142.070007  143.619995  141.369995  142.600006  135.852844
2023-01-05  142.440002  142.500000  140.009995  141.110001  134.433334
2023-01-06  142.380005  144.250000  141.580002  143.699997  136.900803
2023-01-09  144.080002  145.470001  143.399994  143.550003  136.757904
...                ...         ...         ...         ...         ...
2023-11-10  147.440002  149.169998  146.850006  149.020004  149.020004
2023-11-13  148.460007  148.490005  147.350006  148.100006  148.100006
2023-11-14  149.449997  150.809998  149.050003  150.410004  150.410004
2023-11-15  150.399994  153.220001  150.399994  152.580002  152.580002
2023-11-16  153.000000  153.350006  152.130005  153.059998  153.059998

             Volume
Date
2023-01-03  3338600
2023-01-04  3869200
2023-01-05  2866600
2023-01-06  3574000
2023-01-09  3987700
...             ...
2023-11-10  3179000
2023-11-13  2647200
2023-11-14  4321900
2023-11-15  4632500
2023-11-16  3519200

[221 rows x 6 columns]
[*********************100%%**********************]  1 of 1 completed
                  Open        High         Low       Close   Adj Close  \
Date
2023-01-03  141.100006  141.899994  140.479996  141.550003  134.852539
2023-01-04  142.070007  143.619995  141.369995  142.600006  135.852844
2023-01-05  142.440002  142.500000  140.009995  141.110001  134.433334
2023-01-06  142.380005  144.250000  141.580002  143.699997  136.900803
2023-01-09  144.080002  145.470001  143.399994  143.550003  136.757904
...                ...         ...         ...         ...         ...
2023-11-13  148.460007  148.490005  147.350006  148.100006  148.100006
2023-11-14  149.449997  150.809998  149.050003  150.410004  150.410004
2023-11-15  150.399994  153.220001  150.399994  152.580002  152.580002
2023-11-16  153.000000  153.350006  152.130005  153.059998  153.059998
2023-11-17  153.289993  153.500000  152.460007  152.889999  152.889999

             Volume
Date
2023-01-03  3338600
2023-01-04  3869200
2023-01-05  2866600
2023-01-06  3574000
2023-01-09  3987700
...             ...
2023-11-13  2647200
2023-11-14  4321900
2023-11-15  4632500
2023-11-16  3519200
2023-11-17  4426500

[222 rows x 6 columns]

In [ ]:
# Get intra-day data
ticker = "GME"
gme = yf.download(ticker,period="1mo",interval="1h")
print(gme)

gme2 = yf.download(ticker,period="1mo",interval="30m")
print(gme2)

gme3 = yf.download(ticker,period="1d",interval="1m")
gme3.head()
gme3.tail()

gme.describe()

[*********************100%%**********************]  1 of 1 completed
                              Open     High      Low    Close  Adj Close  \
Datetime
2023-10-18 09:30:00-04:00  14.0000  14.1399  13.8202  13.9800    13.9800
2023-10-18 10:30:00-04:00  13.9700  14.2500  13.8101  14.1785    14.1785
2023-10-18 11:30:00-04:00  14.1700  14.1900  13.9450  13.9600    13.9600
2023-10-18 12:30:00-04:00  13.9650  14.2500  13.8800  14.0650    14.0650
2023-10-18 13:30:00-04:00  14.0690  14.1300  13.9700  14.0000    14.0000
...                            ...      ...      ...      ...        ...
2023-11-17 11:30:00-05:00  12.7250  12.8850  12.6650  12.8850    12.8850
2023-11-17 12:30:00-05:00  12.8850  13.0000  12.8750  12.9500    12.9500
2023-11-17 13:30:00-05:00  12.9400  12.9900  12.9200  12.9900    12.9900
2023-11-17 14:30:00-05:00  12.9898  13.0500  12.9700  13.0350    13.0350
2023-11-17 15:30:00-05:00  13.0400  13.0550  12.9300  13.0300    13.0300

                           Volume
Datetime
2023-10-18 09:30:00-04:00  618562
2023-10-18 10:30:00-04:00  592254
2023-10-18 11:30:00-04:00  493685
2023-10-18 12:30:00-04:00  405164
2023-10-18 13:30:00-04:00  330519
...                           ...
2023-11-17 11:30:00-05:00  305444
2023-11-17 12:30:00-05:00  352332
2023-11-17 13:30:00-05:00  205635
2023-11-17 14:30:00-05:00  280542
2023-11-17 15:30:00-05:00  602253

[161 rows x 6 columns]
[*********************100%%**********************]  1 of 1 completed
                        Open     High      Low    Close  Adj Close  Volume
Datetime
2023-10-18 09:30:00  14.0000  14.1399  13.8202  13.9399    13.9399  417489
2023-10-18 10:00:00  13.9440  14.0700  13.8700  13.9800    13.9800  201073
2023-10-18 10:30:00  13.9700  14.0400  13.8101  13.8400    13.8400  219372
2023-10-18 11:00:00  13.8400  14.2500  13.8311  14.1785    14.1785  372882
2023-10-18 11:30:00  14.1700  14.1900  13.9450  14.0500    14.0500  253817
...                      ...      ...      ...      ...        ...     ...
2023-11-17 13:30:00  12.9400  12.9750  12.9250  12.9750    12.9750   94764
2023-11-17 14:00:00  12.9750  12.9900  12.9200  12.9900    12.9900  110871
2023-11-17 14:30:00  12.9898  13.0200  12.9700  13.0102    13.0102  133561
2023-11-17 15:00:00  13.0132  13.0500  13.0100  13.0350    13.0350  146981
2023-11-17 15:30:00  13.0400  13.0550  12.9300  13.0400    13.0400  602253

[299 rows x 6 columns]
[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
count,161.000000,161.000000,161.000000,161.000000,161.000000,1.610000e+02
mean,13.302473,13.408862,13.200650,13.289640,13.289640,4.462606e+05
std,0.487220,0.497949,0.489109,0.490569,0.490569,2.591846e+05
min,12.000000,12.070000,11.825000,12.004600,12.004600,1.114700e+05
25%,12.990000,13.089900,12.900000,12.990000,12.990000,2.707720e+05
50%,13.360000,13.485000,13.260100,13.359100,13.359100,3.755720e+05
75%,13.620000,13.740000,13.520000,13.625000,13.625000,5.508720e+05
max,14.210000,14.400000,14.060000,14.230000,14.230000,1.706381e+06

In [ ]:
# Stock informatio

import yfinance as yf
msft = yf.Ticker("MSFT")
msft.balance_sheet

,2023-06-30,2022-06-30,2021-06-30,2020-06-30
Free Cash Flow,59475000000.0,65149000000.0,56118000000.0,45234000000.0
Repurchase Of Capital Stock,-22245000000.0,-32696000000.0,-27385000000.0,-22968000000.0
Repayment Of Debt,-2750000000.0,-9023000000.0,-3750000000.0,-5518000000.0
Issuance Of Debt,NaN,NaN,NaN,0.0
Issuance Of Capital Stock,1866000000.0,1841000000.0,1693000000.0,1343000000.0
Capital Expenditure,-28107000000.0,-23886000000.0,-20622000000.0,-15441000000.0
End Cash Position,34704000000.0,13931000000.0,14224000000.0,13576000000.0
Beginning Cash Position,13931000000.0,14224000000.0,13576000000.0,11356000000.0
Effect Of Exchange Rate Changes,-194000000.0,-141000000.0,-29000000.0,-201000000.0
Changes In Cash,20967000000.0,-152000000.0,677000000.0,2421000000.0
Financing Cash Flow,-43935000000.0,-58876000000.0,-48486000000.0,-46031000000.0
Cash Flow From Continuing Financing Activities,-43935000000.0,-58876000000.0,-48486000000.0,-46031000000.0
Net Other Financing Charges,-1006000000.0,-863000000.0,-2523000000.0,-3751000000.0
Cash Dividends Paid,-19800000000.0,-18135000000.0,-16521000000.0,-15137000000.0
Common Stock Dividend Paid,-19800000000.0,-18135000000.0,-16521000000.0,-15137000000.0
Net Common Stock Issuance,-20379000000.0,-30855000000.0,-25692000000.0,-21625000000.0
Common Stock Payments,-22245000000.0,-32696000000.0,-27385000000.0,-22968000000.0
Common Stock Issuance,1866000000.0,1841000000.0,1693000000.0,1343000000.0
Net Issuance Payments Of Debt,-2750000000.0,-9023000000.0,-3750000000.0,-5518000000.0
Net Short Term Debt Issuance,NaN,NaN,NaN,0.0
Net Long Term Debt Issuance,-2750000000.0,-9023000000.0,-3750000000.0,-5518000000.0
Long Term Debt Payments,-2750000000.0,-9023000000.0,-3750000000.0,-5518000000.0
Long Term Debt Issuance,NaN,NaN,NaN,0.0
Investing Cash Flow,-22680000000.0,-30311000000.0,-27577000000.0,-12223000000.0
Cash Flow From Continuing Investing Activities,-22680000000.0,-30311000000.0,-27577000000.0,-12223000000.0
Net Other Investing Changes,-3116000000.0,-2825000000.0,-922000000.0,-1241000000.0
Net Investment Purchase And Sale,10213000000.0,18438000000.0,2876000000.0,6980000000.0
Sale Of Investment,47864000000.0,44894000000.0,65800000000.0,84170000000.0
Purchase Of Investment,-37651000000.0,-26456000000.0,-62924000000.0,-77190000000.0
Net Business Purchase And Sale,-1670000000.0,-22038000000.0,-8909000000.0,-2521000000.0
Purchase Of Business,-1670000000.0,-22038000000.0,-8909000000.0,-2521000000.0
Net PPE Purchase And Sale,-28107000000.0,-23886000000.0,-20622000000.0,-15441000000.0
Purchase Of PPE,-28107000000.0,-23886000000.0,-20622000000.0,-15441000000.0
Operating Cash Flow,87582000000.0,89035000000.0,76740000000.0,60675000000.0
Cash Flow From Continuing Operating Activities,87582000000.0,89035000000.0,76740000000.0,60675000000.0
Change In Working Capital,-2388000000.0,446000000.0,-936000000.0,2148000000.0
Change In Other Working Capital,5177000000.0,5805000000.0,2324000000.0,2212000000.0
Change In Other Current Liabilities,2825000000.0,3169000000.0,5551000000.0,2694000000.0
Change In Other Current Assets,-4824000000.0,-3514000000.0,-4391000000.0,-3367000000.0
Change In Payables And Accrued Expense,-2721000000.0,2943000000.0,2798000000.0,3018000000.0
Change In Payable,-2721000000.0,2943000000.0,2798000000.0,3018000000.0
Change In Account Payable,-2721000000.0,2943000000.0,2798000000.0,3018000000.0
Change In Inventory,1242000000.0,-1123000000.0,-737000000.0,168000000.0
Change In Receivables,-4087000000.0,-6834000000.0,-6481000000.0,-2577000000.0
Changes In Account Receivables,-4087000000.0,-6834000000.0,-6481000000.0,-2577000000.0
Stock Based Compensation,9611000000.0,7502000000.0,6118000000.0,5289000000.0
Deferred Tax,-6059000000.0,-5702000000.0,-150000000.0,-3620000000.0
Deferred Income Tax,-6059000000.0,-5702000000.0,-150000000.0,-3620000000.0
Depreciation Amortization Depletion,13861000000.0,14460000000.0,11686000000.0,12796000000.0
Depreciation And Amortization,13861000000.0,14460000000.0,11686000000.0,12796000000.0
Depreciation,13861000000.0,14460000000.0,11686000000.0,12796000000.0
Operating Gains Losses,196000000.0,-409000000.0,-1249000000.0,-219000000.0
Gain Loss On Investment Securities,NaN,NaN,NaN,-219000000.0
Net Income From Continuing Operations,72361000000.0,72738000000.0,61271000000.0,44281000000.0

In [ ]:
msft.cash_flow